// SPEC.md 5장 "시연 시나리오 5케이스 (검산 완료)" 를 그대로 내장한다.
// demo 모드는 백엔드를 전혀 호출하지 않고 이 고정값을 재생한다(SPEC 1장 실행모드 원칙).
import type {
  AccountAssessment,
  ContextAssessment,
  FinalRisk,
  Question,
  ReportPayload,
} from "../types";

export interface DemoCase {
  id: string;
  emoji: string;
  title: string;
  subtitle: string;
  input: {
    customerName: string;
    customerAccount: string;
    payeeBank: string;
    payeeName: string;
    payeeAccount: string;
    amount: number;
  };
  account: AccountAssessment;
  /** 위험도 분석 그래프(RiskBreakdown)용 2단계 상세 데이터. 질문 자체가 없는
   * 케이스(예: 확인 1탭 경로)는 null. */
  context: ContextAssessment | null;
  questions: Question[];
  /** M5 화면 AI 첫 인사말에 덧붙이는 안내 문구. */
  chatHint: string;
  /** M5에서 재생할 대본: 버튼을 누를 때마다 한 턴(사용자 발화 -> AI 응답)씩 진행된다.
   * 비어있으면 이 케이스는 대화 없이 바로 결과로 넘어간다(저위험 확인 경로). 마지막 턴의
   * ai 텍스트가 곧 M6에 표시되는 agentReply와 같아야 한다. */
  chatTurns: { user: string; ai: string }[];
  agentReply: string | null;
  final: FinalRisk;
  report: ReportPayload | null;
  /** demo 모드에서 결과와 무관하게 아무 버튼이나 눌러도 다음 화면으로 넘어가긴 하지만,
   * 이 케이스의 "각본"과 실제로 맞아떨어지는 선택지가 뭔지 화면에 하이라이트해주기 위한 값.
   * question_id -> 그 시나리오가 실제로 상정한 choice_id. */
  scriptedAnswers: Record<string, string>;
}

const empathyChoices = (extra?: { label: string; weight: number }[]) => [
  { choice_id: "normal_known", label: "직접 아는 지인·가족에게 보내요", weight: 0, hard_override: false },
  { choice_id: "normal_trade", label: "물건 구매/판매 대금이에요", weight: 0, hard_override: false },
  { choice_id: "normal_settlement", label: "임대료·잔금 등 정산 목적이에요", weight: 0, hard_override: false },
  { choice_id: "risky_offer", label: "최근 대출·투자 안내를 받고 보내요", weight: 25, hard_override: false },
  { choice_id: "risky_text_only", label: "아는 사람이라는데 문자로만 연락돼요", weight: 25, hard_override: false },
  ...(extra ?? []).map((c, i) => ({ choice_id: `extra_${i}`, ...c, hard_override: false })),
];

const safetyQuestion = (): Question => ({
  question_id: "safety",
  prompt: "혹시 검찰·금감원이라며 '안전계좌'로 옮기라거나, 앱 설치를 안내받으셨나요?",
  choices: [
    { choice_id: "safety_no", label: "아니요", weight: 0, hard_override: false },
    { choice_id: "safety_yes", label: "비슷한 안내를 받았어요", weight: 50, hard_override: true },
  ],
});

function empathyQuestion(customerName: string): Question {
  return {
    question_id: "empathy",
    prompt: `${customerName}님, 이번 송금은 어떤 이유로 보내시는 걸까요?`,
    choices: empathyChoices(),
  };
}

export const DEMO_CASES: DemoCase[] = [
  {
    id: "case1",
    emoji: "🔴",
    title: "검찰사칭",
    subtitle: "적금 해지 후 2,000만원 · 신고이력 계좌",
    input: {
      customerName: "남용환",
      customerAccount: "351-0000-0001",
      payeeBank: "미래에셋증권",
      payeeName: "남용환",
      payeeAccount: "010-6660-98261",
      amount: 20_000_000,
    },
    account: {
      signals: [
        { signal: "payee_fraud", hit: true, score: 40, detail: "사기신고 3건" },
        { signal: "amount_anomaly", hit: true, score: 25, detail: "평소 대비 66.7배" },
        { signal: "fund_source", hit: true, score: 25, detail: "적금 해지 후 24시간 이내 자금이동" },
        { signal: "payee_freshness", hit: false, score: 0, detail: "-" },
        { signal: "limit_change", hit: false, score: 0, detail: "-" },
        { signal: "velocity", hit: false, score: 0, detail: "-" },
        { signal: "device", hit: false, score: 0, detail: "-" },
        { signal: "time_pattern", hit: false, score: 0, detail: "-" },
      ],
      total_score: 90,
      level: "고",
    },
    context: {
      answers: [
        { question_id: "empathy", choice_id: "normal_known", choice_weight: 0, hard_override: false },
        { question_id: "safety", choice_id: "safety_yes", choice_weight: 50, hard_override: true },
      ],
      used_input_or_attachment: true,
      rag: {
        signal: "scenario",
        hit: true,
        matched_type: "기관사칭",
        matched_id: "S02",
        similarity: 0.87,
        score: 50,
        risk_signals: ["안전계좌", "자산보호"],
        source: "경찰청 월간피싱 zero S02",
        candidates: [
          { scenario_id: "S02", matched_type: "기관사칭", similarity: 0.87 },
          { scenario_id: "S03", matched_type: "기관사칭", similarity: 0.68 },
          { scenario_id: "S10", matched_type: "원격제어형", similarity: 0.64 },
          { scenario_id: "S01", matched_type: "기관사칭", similarity: 0.61 },
          { scenario_id: "S06", matched_type: "협박형", similarity: 0.48 },
          { scenario_id: "S04", matched_type: "대출사기", similarity: 0.48 },
          { scenario_id: "S07", matched_type: "스미싱", similarity: 0.41 },
          { scenario_id: "S05", matched_type: "메신저피싱", similarity: 0.4 },
          { scenario_id: "S09", matched_type: "취업사기", similarity: 0.38 },
          { scenario_id: "S08", matched_type: "몸캠피싱", similarity: 0.33 },
        ],
      },
      total_score: 110,
      level: "고",
      hard_override: true,
    },
    questions: [empathyQuestion("남용환"), safetyQuestion()],
    chatHint: "상황 설명이나 안내문자 캡처를 올려주세요.",
    scriptedAnswers: { empathy: "normal_known", safety: "safety_yes" },
    chatTurns: [
      {
        user: "검찰이라며 제 계좌가 범죄에 연루됐다고 안전계좌로 옮기라고 했어요",
        ai: "혹시 전화 주신 분이 신분증이나 공문 같은 걸 보여주셨나요? 안내문자나 캡처가 있다면 같이 보여주시겠어요?",
      },
      {
        user: "네, 검찰 공무원증 사진을 보내줬고 '지금 안전계좌로 옮기지 않으면 계좌가 동결된다'는 문자도 왔어요",
        ai: "말씀해주신 내용과 캡처를 확인해보니 검찰·금감원을 사칭해 '안전계좌'로 유도하는 사례와 매우 유사해요. 지금 이체를 잠시 멈추고 가까운 영업점에서 확인해보시는 게 좋겠어요.",
      },
    ],
    agentReply:
      "말씀해주신 내용과 캡처를 확인해보니 검찰·금감원을 사칭해 '안전계좌'로 유도하는 사례와 매우 유사해요. 지금 이체를 잠시 멈추고 가까운 영업점에서 확인해보시는 게 좋겠어요.",
    final: {
      account_level: "고",
      context_level: "고",
      final: "위험",
      hard_override: true,
      reasons: [
        "사기신고 3건(+40)",
        "평소 대비 66.7배(+25)",
        "적금 해지 후 24시간 이내 자금이동(+25)",
        "기관 안내(안전계좌) 응답(+50)",
        "대화 입력·첨부(+10)",
        "RAG 매칭: 기관사칭(유사도 0.87, 경찰청 월간피싱 zero S02)",
        "결정적 피싱징후 감지: 위험신호 직접 확인",
      ],
      action: "강력 경고 + 영업점 연계 리포트 생성(고객이 원하면 지연이체로 진행 가능)",
    },
    report: {
      report_id: "RPT-20260811-001",
      generated_at: "2026-08-11T01:15:00+09:00",
      customer_name: "남용환",
      customer_phone_masked: "010-****-****",
      customer_account_masked: "351-****-0001",
      payee_bank: "미래에셋증권",
      payee_account: "010-6660-98261",
      payee_name: "남용환",
      amount: 20_000_000,
      attempted_at: "2026-08-11T01:10:00+09:00",
      final: {
        account_level: "고",
        context_level: "고",
        final: "위험",
        hard_override: true,
        reasons: [],
        action: "강력 경고 + 영업점 연계 리포트 생성(고객이 원하면 지연이체로 진행 가능)",
      },
      account_reasons: ["위험계좌 정보(+40)", "평소 대비 고액(+25)", "자금이동 적금해지(+25)"],
      conversation_summary: "\"검찰이 안전계좌로 옮기라 했다\"고 응답, 안내문자 캡처 1건 업로드",
      attachments_present: true,
      rag: {
        signal: "scenario",
        hit: true,
        matched_type: "기관사칭",
        matched_id: "S02",
        similarity: 0.87,
        score: 50,
        risk_signals: ["안전계좌", "자산보호"],
        source: "경찰청 월간피싱 zero S02",
        candidates: [
          { scenario_id: "S02", matched_type: "기관사칭", similarity: 0.87 },
          { scenario_id: "S03", matched_type: "기관사칭", similarity: 0.68 },
          { scenario_id: "S10", matched_type: "원격제어형", similarity: 0.64 },
          { scenario_id: "S01", matched_type: "기관사칭", similarity: 0.61 },
          { scenario_id: "S06", matched_type: "협박형", similarity: 0.48 },
          { scenario_id: "S04", matched_type: "대출사기", similarity: 0.48 },
          { scenario_id: "S07", matched_type: "스미싱", similarity: 0.41 },
          { scenario_id: "S05", matched_type: "메신저피싱", similarity: 0.4 },
          { scenario_id: "S09", matched_type: "취업사기", similarity: 0.38 },
          { scenario_id: "S08", matched_type: "몸캠피싱", similarity: 0.33 },
        ],
      },
      recommendation: "대면 본인확인 및 통화상대 진위 확인, 필요시 지급정지·112 안내",
      account: {
        signals: [
          { signal: "payee_fraud", hit: true, score: 40, detail: "사기신고 3건" },
          { signal: "amount_anomaly", hit: true, score: 25, detail: "평소 대비 66.7배" },
          { signal: "fund_source", hit: true, score: 25, detail: "적금 해지 후 24시간 이내 자금이동" },
          { signal: "payee_freshness", hit: false, score: 0, detail: "-" },
          { signal: "limit_change", hit: false, score: 0, detail: "-" },
          { signal: "velocity", hit: false, score: 0, detail: "-" },
          { signal: "device", hit: false, score: 0, detail: "-" },
          { signal: "time_pattern", hit: false, score: 0, detail: "-" },
        ],
        total_score: 90,
        level: "고",
      },
      context: {
        answers: [
          { question_id: "empathy", choice_id: "normal_known", choice_weight: 0, hard_override: false },
          { question_id: "safety", choice_id: "safety_yes", choice_weight: 50, hard_override: true },
        ],
        used_input_or_attachment: true,
        rag: {
          signal: "scenario",
          hit: true,
          matched_type: "기관사칭",
          matched_id: "S02",
          similarity: 0.87,
          score: 50,
          risk_signals: ["안전계좌", "자산보호"],
          source: "경찰청 월간피싱 zero S02",
          candidates: [
            { scenario_id: "S02", matched_type: "기관사칭", similarity: 0.87 },
            { scenario_id: "S03", matched_type: "기관사칭", similarity: 0.68 },
            { scenario_id: "S10", matched_type: "원격제어형", similarity: 0.64 },
            { scenario_id: "S01", matched_type: "기관사칭", similarity: 0.61 },
            { scenario_id: "S06", matched_type: "협박형", similarity: 0.48 },
            { scenario_id: "S04", matched_type: "대출사기", similarity: 0.48 },
            { scenario_id: "S07", matched_type: "스미싱", similarity: 0.41 },
            { scenario_id: "S05", matched_type: "메신저피싱", similarity: 0.4 },
            { scenario_id: "S09", matched_type: "취업사기", similarity: 0.38 },
            { scenario_id: "S08", matched_type: "몸캠피싱", similarity: 0.33 },
          ],
        },
        total_score: 110,
        level: "고",
        hard_override: true,
      },
    },
  },
  {
    id: "case2",
    emoji: "🔴",
    title: "대환대출",
    subtitle: "한도 상향 직후 500만원 · 신규계좌",
    input: {
      customerName: "김도윤",
      customerAccount: "351-0000-0002",
      payeeBank: "신한은행",
      payeeName: "정대환",
      payeeAccount: "110-452-118834",
      amount: 5_000_000,
    },
    account: {
      signals: [
        { signal: "payee_fraud", hit: false, score: 0, detail: "-" },
        { signal: "amount_anomaly", hit: true, score: 25, detail: "평소 대비 25.0배" },
        { signal: "fund_source", hit: false, score: 0, detail: "-" },
        { signal: "payee_freshness", hit: true, score: 20, detail: "개설 5일" },
        { signal: "limit_change", hit: true, score: 20, detail: "24시간 내 이체한도 상향" },
        { signal: "velocity", hit: false, score: 0, detail: "-" },
        { signal: "device", hit: false, score: 0, detail: "-" },
        { signal: "time_pattern", hit: false, score: 0, detail: "-" },
      ],
      total_score: 65,
      level: "고",
    },
    context: {
      answers: [
        { question_id: "empathy", choice_id: "risky_offer", choice_weight: 25, hard_override: false },
        { question_id: "safety", choice_id: "safety_no", choice_weight: 0, hard_override: false },
      ],
      used_input_or_attachment: true,
      rag: {
        signal: "scenario",
        hit: true,
        matched_type: "대출사기",
        matched_id: "S04",
        similarity: 0.82,
        score: 50,
        risk_signals: ["선입금요구", "한도상향유도"],
        source: "NH 제작 S04",
        candidates: [
          { scenario_id: "S04", matched_type: "대출사기", similarity: 0.82 },
          { scenario_id: "S09", matched_type: "취업사기", similarity: 0.61 },
          { scenario_id: "S06", matched_type: "협박형", similarity: 0.54 },
          { scenario_id: "S05", matched_type: "메신저피싱", similarity: 0.48 },
          { scenario_id: "S01", matched_type: "기관사칭", similarity: 0.44 },
          { scenario_id: "S03", matched_type: "기관사칭", similarity: 0.43 },
          { scenario_id: "S02", matched_type: "기관사칭", similarity: 0.42 },
          { scenario_id: "S07", matched_type: "스미싱", similarity: 0.38 },
          { scenario_id: "S10", matched_type: "원격제어형", similarity: 0.37 },
          { scenario_id: "S08", matched_type: "몸캠피싱", similarity: 0.36 },
        ],
      },
      total_score: 85,
      level: "고",
      hard_override: false,
    },
    questions: [empathyQuestion("김도윤"), safetyQuestion()],
    chatHint: "대출 상담 문자나 통화 내용을 올려주세요.",
    scriptedAnswers: { empathy: "risky_offer", safety: "safety_no" },
    chatTurns: [
      {
        user: "저금리로 대환대출 해준다고 해서 먼저 상환금부터 보내려고 해요",
        ai: "혹시 그 안내를 어디로 받으셨나요? 은행 공식 앱이나 창구가 아니라 문자·전화로 먼저 연락이 왔다면 조금 더 확인해볼게요.",
      },
      {
        user: "네, 저축은행 직원이라면서 문자로 먼저 연락이 왔고 한도도 이미 올려놨다고 했어요",
        ai: "저금리 대환대출을 이유로 먼저 돈을 보내달라는 절차는 정상적인 은행 대출 절차와 달라요. 지금 이체를 멈추고 은행 공식 채널로 다시 확인해보시는 게 안전해요.",
      },
    ],
    agentReply:
      "저금리 대환대출을 이유로 먼저 돈을 보내달라는 절차는 정상적인 은행 대출 절차와 달라요. 지금 이체를 멈추고 은행 공식 채널로 다시 확인해보시는 게 안전해요.",
    final: {
      account_level: "고",
      context_level: "고",
      final: "위험",
      hard_override: false,
      reasons: [
        "평소 대비 25.0배(+25)",
        "개설 5일(+20)",
        "24시간 내 이체한도 상향(+20)",
        "대출·투자 안내 응답(+25)",
        "대화 입력(+10)",
        "RAG 매칭: 대출사기(유사도 0.82, NH 제작 S04)",
      ],
      action: "강력 경고 + 영업점 연계 리포트 생성(고객이 원하면 지연이체로 진행 가능)",
    },
    report: {
      report_id: "RPT-20260812-002",
      generated_at: "2026-08-12T10:05:00+09:00",
      customer_name: "김도윤",
      customer_phone_masked: "010-****-0002",
      customer_account_masked: "351-****-0002",
      payee_bank: "신한은행",
      payee_account: "110-452-118834",
      payee_name: "정대환",
      amount: 5_000_000,
      attempted_at: "2026-08-12T10:00:00+09:00",
      final: {
        account_level: "고",
        context_level: "고",
        final: "위험",
        hard_override: false,
        reasons: [],
        action: "강력 경고 + 영업점 연계 리포트 생성(고객이 원하면 지연이체로 진행 가능)",
      },
      account_reasons: ["평소 대비 고액(+25)", "신규계좌(+20)", "이체한도 상향(+20)"],
      conversation_summary: "\"저금리 대환대출 안내를 받고 먼저 상환금을 보내려 한다\"고 응답, 문자 캡처 업로드",
      attachments_present: true,
      rag: {
        signal: "scenario",
        hit: true,
        matched_type: "대출사기",
        matched_id: "S04",
        similarity: 0.82,
        score: 50,
        risk_signals: ["선입금요구", "한도상향유도"],
        source: "NH 제작 S04",
        candidates: [
          { scenario_id: "S04", matched_type: "대출사기", similarity: 0.82 },
          { scenario_id: "S09", matched_type: "취업사기", similarity: 0.61 },
          { scenario_id: "S06", matched_type: "협박형", similarity: 0.54 },
          { scenario_id: "S05", matched_type: "메신저피싱", similarity: 0.48 },
          { scenario_id: "S01", matched_type: "기관사칭", similarity: 0.44 },
          { scenario_id: "S03", matched_type: "기관사칭", similarity: 0.43 },
          { scenario_id: "S02", matched_type: "기관사칭", similarity: 0.42 },
          { scenario_id: "S07", matched_type: "스미싱", similarity: 0.38 },
          { scenario_id: "S10", matched_type: "원격제어형", similarity: 0.37 },
          { scenario_id: "S08", matched_type: "몸캠피싱", similarity: 0.36 },
        ],
      },
      recommendation: "대면 본인확인 및 대출 상담 경위 재확인, 필요시 지급정지·112 안내",
      account: {
        signals: [
          { signal: "payee_fraud", hit: false, score: 0, detail: "-" },
          { signal: "amount_anomaly", hit: true, score: 25, detail: "평소 대비 25.0배" },
          { signal: "fund_source", hit: false, score: 0, detail: "-" },
          { signal: "payee_freshness", hit: true, score: 20, detail: "개설 5일" },
          { signal: "limit_change", hit: true, score: 20, detail: "24시간 내 이체한도 상향" },
          { signal: "velocity", hit: false, score: 0, detail: "-" },
          { signal: "device", hit: false, score: 0, detail: "-" },
          { signal: "time_pattern", hit: false, score: 0, detail: "-" },
        ],
        total_score: 65,
        level: "고",
      },
      context: {
        answers: [
          { question_id: "empathy", choice_id: "risky_offer", choice_weight: 25, hard_override: false },
          { question_id: "safety", choice_id: "safety_no", choice_weight: 0, hard_override: false },
        ],
        used_input_or_attachment: true,
        rag: {
          signal: "scenario",
          hit: true,
          matched_type: "대출사기",
          matched_id: "S04",
          similarity: 0.82,
          score: 50,
          risk_signals: ["선입금요구", "한도상향유도"],
          source: "NH 제작 S04",
          candidates: [
            { scenario_id: "S04", matched_type: "대출사기", similarity: 0.82 },
            { scenario_id: "S09", matched_type: "취업사기", similarity: 0.61 },
            { scenario_id: "S06", matched_type: "협박형", similarity: 0.54 },
            { scenario_id: "S05", matched_type: "메신저피싱", similarity: 0.48 },
            { scenario_id: "S01", matched_type: "기관사칭", similarity: 0.44 },
            { scenario_id: "S03", matched_type: "기관사칭", similarity: 0.43 },
            { scenario_id: "S02", matched_type: "기관사칭", similarity: 0.42 },
            { scenario_id: "S07", matched_type: "스미싱", similarity: 0.38 },
            { scenario_id: "S10", matched_type: "원격제어형", similarity: 0.37 },
            { scenario_id: "S08", matched_type: "몸캠피싱", similarity: 0.36 },
          ],
        },
        total_score: 85,
        level: "고",
        hard_override: false,
      },
    },
  },
  {
    id: "case3",
    emoji: "🔴",
    title: "메신저피싱",
    subtitle: "카톡 받고 100만원 · 신규계좌 (계좌점수 낮아도 맥락으로 포착)",
    input: {
      customerName: "남용환",
      customerAccount: "351-0000-0001",
      payeeBank: "카카오뱅크",
      payeeName: "황민석",
      payeeAccount: "301-8827-4410",
      amount: 1_000_000,
    },
    account: {
      signals: [
        { signal: "payee_fraud", hit: false, score: 0, detail: "-" },
        { signal: "amount_anomaly", hit: true, score: 8, detail: "평소 대비 3.3배" },
        { signal: "fund_source", hit: false, score: 0, detail: "-" },
        { signal: "payee_freshness", hit: true, score: 20, detail: "개설 6일" },
        { signal: "limit_change", hit: false, score: 0, detail: "-" },
        { signal: "velocity", hit: false, score: 0, detail: "-" },
        { signal: "device", hit: false, score: 0, detail: "-" },
        { signal: "time_pattern", hit: false, score: 0, detail: "-" },
      ],
      total_score: 28,
      level: "저",
    },
    context: {
      answers: [{ question_id: "empathy", choice_id: "risky_text_only", choice_weight: 30, hard_override: false }],
      used_input_or_attachment: true,
      rag: {
        signal: "scenario",
        hit: true,
        matched_type: "메신저피싱",
        matched_id: "S05",
        similarity: 0.6,
        score: 30,
        risk_signals: ["통화회피", "문자로만연락"],
        source: "경찰청 월간피싱 zero S05",
        candidates: [
          { scenario_id: "S05", matched_type: "메신저피싱", similarity: 0.6 },
          { scenario_id: "S08", matched_type: "몸캠피싱", similarity: 0.4 },
          { scenario_id: "S07", matched_type: "스미싱", similarity: 0.27 },
          { scenario_id: "S10", matched_type: "원격제어형", similarity: 0.21 },
          { scenario_id: "S06", matched_type: "협박형", similarity: 0.19 },
          { scenario_id: "S03", matched_type: "기관사칭", similarity: 0.17 },
          { scenario_id: "S01", matched_type: "기관사칭", similarity: 0.17 },
          { scenario_id: "S02", matched_type: "기관사칭", similarity: 0.14 },
          { scenario_id: "S09", matched_type: "취업사기", similarity: 0.13 },
          { scenario_id: "S04", matched_type: "대출사기", similarity: 0.11 },
        ],
      },
      total_score: 70,
      level: "고",
      hard_override: false,
    },
    questions: [empathyQuestion("남용환")],
    chatHint: "대화 캡처나 상황을 적어주세요.",
    scriptedAnswers: { empathy: "risky_text_only" },
    chatTurns: [
      {
        user: "아는 사람인데 전화는 안 받고 문자로만 연락돼요",
        ai: "혹시 평소 말투나 프로필 사진이 그대로인가요? 최근 대화 내용을 조금 더 보여주실 수 있을까요?",
      },
      {
        user: "말투가 평소랑 좀 다르고, 급하게 돈이 필요하다는 말만 계속해요",
        ai: "직접 통화는 안 되고 문자로만 연락된다는 점이 걸려요. 실제로 아시는 분이 맞는지 전화나 영상통화로 한 번 더 확인해보시는 게 좋겠어요.",
      },
    ],
    agentReply:
      "직접 통화는 안 되고 문자로만 연락된다는 점이 걸려요. 실제로 아시는 분이 맞는지 전화나 영상통화로 한 번 더 확인해보시는 게 좋겠어요.",
    final: {
      account_level: "저",
      context_level: "고",
      final: "위험",
      hard_override: false,
      reasons: [
        "평소 대비 3.3배(+8)",
        "개설 6일(+20)",
        "아는 사람이라는데 문자로만 연락됨(+30)",
        "대화 입력(+10)",
        "RAG 매칭: 메신저피싱(유사도 0.60, 경찰청 월간피싱 zero S05)",
      ],
      action: "강력 경고 + 영업점 연계 리포트 생성(고객이 원하면 지연이체로 진행 가능)",
    },
    report: {
      report_id: "RPT-20260813-003",
      generated_at: "2026-08-13T20:20:00+09:00",
      customer_name: "남용환",
      customer_phone_masked: "010-****-0001",
      customer_account_masked: "351-****-0001",
      payee_bank: "카카오뱅크",
      payee_account: "301-8827-4410",
      payee_name: "황민석",
      amount: 1_000_000,
      attempted_at: "2026-08-13T20:15:00+09:00",
      final: {
        account_level: "저",
        context_level: "고",
        final: "위험",
        hard_override: false,
        reasons: [],
        action: "강력 경고 + 영업점 연계 리포트 생성(고객이 원하면 지연이체로 진행 가능)",
      },
      account_reasons: ["평소 대비 이상거래(+8)", "신규계좌(+20)"],
      conversation_summary: "\"아는 사람인데 문자로만 연락된다\"고 응답, 대화 캡처 업로드",
      attachments_present: true,
      rag: {
        signal: "scenario",
        hit: true,
        matched_type: "메신저피싱",
        matched_id: "S05",
        similarity: 0.6,
        score: 30,
        risk_signals: ["통화회피", "문자로만연락"],
        source: "경찰청 월간피싱 zero S05",
        candidates: [
          { scenario_id: "S05", matched_type: "메신저피싱", similarity: 0.6 },
          { scenario_id: "S08", matched_type: "몸캠피싱", similarity: 0.4 },
          { scenario_id: "S07", matched_type: "스미싱", similarity: 0.27 },
          { scenario_id: "S10", matched_type: "원격제어형", similarity: 0.21 },
          { scenario_id: "S06", matched_type: "협박형", similarity: 0.19 },
          { scenario_id: "S03", matched_type: "기관사칭", similarity: 0.17 },
          { scenario_id: "S01", matched_type: "기관사칭", similarity: 0.17 },
          { scenario_id: "S02", matched_type: "기관사칭", similarity: 0.14 },
          { scenario_id: "S09", matched_type: "취업사기", similarity: 0.13 },
          { scenario_id: "S04", matched_type: "대출사기", similarity: 0.11 },
        ],
      },
      recommendation: "통화상대 재확인(영상통화 권유), 필요시 지급정지·112 안내",
      account: {
        signals: [
          { signal: "payee_fraud", hit: false, score: 0, detail: "-" },
          { signal: "amount_anomaly", hit: true, score: 8, detail: "평소 대비 3.3배" },
          { signal: "fund_source", hit: false, score: 0, detail: "-" },
          { signal: "payee_freshness", hit: true, score: 20, detail: "개설 6일" },
          { signal: "limit_change", hit: false, score: 0, detail: "-" },
          { signal: "velocity", hit: false, score: 0, detail: "-" },
          { signal: "device", hit: false, score: 0, detail: "-" },
          { signal: "time_pattern", hit: false, score: 0, detail: "-" },
        ],
        total_score: 28,
        level: "저",
      },
      context: {
        answers: [{ question_id: "empathy", choice_id: "risky_text_only", choice_weight: 30, hard_override: false }],
        used_input_or_attachment: true,
        rag: {
          signal: "scenario",
          hit: true,
          matched_type: "메신저피싱",
          matched_id: "S05",
          similarity: 0.6,
          score: 30,
          risk_signals: ["통화회피", "문자로만연락"],
          source: "경찰청 월간피싱 zero S05",
          candidates: [
            { scenario_id: "S05", matched_type: "메신저피싱", similarity: 0.6 },
            { scenario_id: "S08", matched_type: "몸캠피싱", similarity: 0.4 },
            { scenario_id: "S07", matched_type: "스미싱", similarity: 0.27 },
            { scenario_id: "S10", matched_type: "원격제어형", similarity: 0.21 },
            { scenario_id: "S06", matched_type: "협박형", similarity: 0.19 },
            { scenario_id: "S03", matched_type: "기관사칭", similarity: 0.17 },
            { scenario_id: "S01", matched_type: "기관사칭", similarity: 0.17 },
            { scenario_id: "S02", matched_type: "기관사칭", similarity: 0.14 },
            { scenario_id: "S09", matched_type: "취업사기", similarity: 0.13 },
            { scenario_id: "S04", matched_type: "대출사기", similarity: 0.11 },
          ],
        },
        total_score: 70,
        level: "고",
        hard_override: false,
      },
    },
  },
  {
    id: "case4",
    emoji: "🟢",
    title: "중고거래",
    subtitle: "15만원 · 신규계좌 (정상, 3초 통과)",
    input: {
      customerName: "남용환",
      customerAccount: "351-0000-0001",
      payeeBank: "국민은행",
      payeeName: "서준혁",
      payeeAccount: "552-102-993841",
      amount: 150_000,
    },
    account: {
      signals: [
        { signal: "payee_fraud", hit: false, score: 0, detail: "-" },
        { signal: "amount_anomaly", hit: false, score: 0, detail: "평소 대비 0.5배" },
        { signal: "fund_source", hit: false, score: 0, detail: "-" },
        { signal: "payee_freshness", hit: true, score: 20, detail: "개설 4일" },
        { signal: "limit_change", hit: false, score: 0, detail: "-" },
        { signal: "velocity", hit: false, score: 0, detail: "-" },
        { signal: "device", hit: false, score: 0, detail: "-" },
        { signal: "time_pattern", hit: false, score: 0, detail: "-" },
      ],
      total_score: 20,
      level: "저",
    },
    context: null,
    questions: [],
    chatHint: "",
    scriptedAnswers: {},
    chatTurns: [],
    agentReply: null,
    final: {
      account_level: "저",
      context_level: "저",
      final: "안전",
      hard_override: false,
      reasons: ["개설 4일(+20)"],
      action: "확인 1탭으로 송금 진행",
    },
    report: null,
  },
  {
    id: "case5",
    emoji: "🟢",
    title: "부동산 잔금",
    subtitle: "5,000만원 · 신규계좌 (금액 커도 정상 사유면 안 막음)",
    input: {
      customerName: "박지훈",
      customerAccount: "351-0000-0004",
      payeeBank: "우리은행",
      payeeName: "(주)한빛공인중개법인 에스크로",
      payeeAccount: "088-19-284755",
      amount: 50_000_000,
    },
    account: {
      signals: [
        { signal: "payee_fraud", hit: false, score: 0, detail: "-" },
        { signal: "amount_anomaly", hit: true, score: 25, detail: "평소 대비 16.7배" },
        { signal: "fund_source", hit: false, score: 0, detail: "-" },
        { signal: "payee_freshness", hit: true, score: 20, detail: "개설 3일" },
        { signal: "limit_change", hit: false, score: 0, detail: "-" },
        { signal: "velocity", hit: false, score: 0, detail: "-" },
        { signal: "device", hit: false, score: 0, detail: "-" },
        { signal: "time_pattern", hit: false, score: 0, detail: "-" },
      ],
      total_score: 45,
      level: "중",
    },
    context: {
      answers: [{ question_id: "empathy", choice_id: "normal_settlement", choice_weight: 0, hard_override: false }],
      used_input_or_attachment: false,
      rag: null,
      total_score: 0,
      level: "저",
      hard_override: false,
    },
    questions: [empathyQuestion("박지훈")],
    chatHint: "",
    scriptedAnswers: { empathy: "normal_settlement" },
    chatTurns: [],
    agentReply: null,
    final: {
      account_level: "중",
      context_level: "저",
      final: "안전",
      hard_override: false,
      reasons: ["평소 대비 16.7배(+25)", "개설 3일(+20)"],
      action: "확인 1탭으로 송금 진행",
    },
    report: null,
  },
];

export function findDemoCase(id: string): DemoCase {
  const found = DEMO_CASES.find((c) => c.id === id);
  if (!found) throw new Error(`unknown demo case: ${id}`);
  return found;
}
